# Generated by Django 5.2.12 on 2026-05-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0005_releaserequest_warning_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalasset',
            name='document_file',
            field=models.FileField(blank=True, help_text='Upload any file type for document assets', null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='digitalasset',
            name='encrypted_data',
            field=models.TextField(blank=True),
        ),
    ]
